### ISSUE TITLE
Windows defender flags file

### ISSUE THREAD

**Issue by wooooooooooooooowastaken** [Briles/scheme-sweet#1]
Windows Defender is flagging one of the files in the repository as Trojan:Win32/Sprisky.U!cl. . I'm sure it's a false positive but it causes a download failure in Chrome.  **Excellent tool by the way.**

____
### MS Link
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Sprisky.U!cl

____
### Screenshot 1/3
![screenshot-20180121-231658](https://user-images.githubusercontent.com/33776815/35205400-f160a84c-ff02-11e7-9d3a-70c0642784ec.png)
____

### Screenshot 2/3
![screenshot-20180121-230116-windows-defender-security-center](https://user-images.githubusercontent.com/33776815/35205402-f1764828-ff02-11e7-95cd-e8bc08e1b440.png)    
____
### Screenshot 3/3
![screenshot-20180121-230635-trojanwin32spriskyu cl-threat-description-windows-defender-security-intelli](https://user-images.githubusercontent.com/33776815/35205401-f16b4180-ff02-11e7-8b0d-c876e7f31b06.png)    
____

**Comment by Briles** [comment]
Windows is misidentifying it as a virus. I don’t think there’s anything I can do about this from my end of things. If you have the option of submitting a report to mark it as safe, please do so.
